review:
  rules:
    - when: pull_request_opened
      assign:
        reviewers:
          - "maintainer1"
          - "maintainer2"
      add_labels:
        - "needs-review"
      comment: |
        ## 변경사항 설명
        {description}

        ## 테스트
        - [ ] 단위 테스트 통과
        - [ ] 통합 테스트 통과

        ## 체크리스트
        - [ ] 코드 스타일 가이드 준수
        - [ ] 문서 업데이트
        - [ ] 불필요한 주석 제거
